version: "3.8"
services:
  flask-api:
    build:
      context: ./roadmap/backend  # Carpeta que contendrá el proyecto Flask clonado
    ports:
      - "5000:5000"
    networks:
      - app-network

  springboot-api:
    build:
      context: ./springboot-api  # Carpeta que contendrá el proyecto Spring Boot clonado
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge